SELECT RTRIM([RI].[RIUSRGROUP].[GROUP_SEQ_NO]) as GROUP_SEQ_NO,
       RTRIM([RI].[RIUSRGROUP].[RI_GROUP_NAME]) as RI_GROUP_NAME,
       RTRIM([RI].[RIUSRGROUP].[DEFAULT_USER]) as DEFAULT_USER
  FROM [RIAPPLDB].[RI].[RIUSRGROUP]
  order by [GROUP_SEQ_NO]