SELECT        RTRIM(R.USER_IDENTITY) as USER_IDENTITY,
              RTRIM(R.RI_USER_NAME) as RI_USER_NAME,
              RTRIM(R.E_MAIL) as E_MAIL,
              RTRIM(AP.AUTH_PROF_NAME) as AUTH_PROF_NAME,
			  CASE R.USER_STATUS WHEN 'ACT' THEN 'Active' WHEN 'DIS' THEN 'Disabled' END AS [Status]

FROM          [RI].[RIUSER] R
INNER JOIN    [RI].[RIAUTHPROF] AP ON R.[AUTH_PRF_SEQ_NUM] = AP.[AUTH_PRF_SEQ_NUM] 
