;WITH ACTIVITIES AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'ACT'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'ACT')

, [PARTY APPEAL] AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'APL'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'APL')

, [ASSETS] AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'AST'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'AST')

, [CLAIM HEADER] AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'CLM'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'CLM')  
							                             
, [CONTRACT] AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'CNT'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'CNT')
                            
,[Technical Documents] AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'DOC'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'DOC')                         
                              
,[CA Items] AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'FIN'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'FIN')                                                                                     
                             
,[Financial Migration] AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'FMG'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'FMG')     
                              
,[Financial Transactions] AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'FTR'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'FTR')   

, [GL ACCOUNTING] AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'GLA'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'GLA')                            
 
 , [GL INTERFACE] AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'GLI'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'GLI')  
							                                                           
 ,[Manual Entries] AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'MAN'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'MAN')                               
                                                                                   
  ,[Processing Management] AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'PMG'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'PMG')                               
 
 ,[Party] AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'PRT'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'PRT')   

 ,[System Management] AS (SELECT DISTINCT AP.AUTH_PROF_NAME, CASE CNT WHEN 2 THEN 'Update/View' ELSE RIGHT_LEVEL END AS RIGHT_LEVEL
                              FROM RIAPPLDB.RI.RIAUTHENTT R
                              LEFT JOIN [RI].[RIAUTHPROF] AP on R.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
                              JOIN (SELECT DISTINCT RI.RIAUTHPROF.AUTH_PROF_NAME,COUNT(RIGHT_LEVEL)AS CNT from RIAPPLDB.RI.RIAUTHENTT
                              LEFT JOIN [RI].[RIAUTHPROF] on RI.RIAUTHENTT.AUTH_PRF_SEQ_NUM= RI.RIAUTHPROF.AUTH_PRF_SEQ_NUM
                              WHERE INVEN_CATEGORY = 'SYS'
                              GROUP BY RI.RIAUTHPROF.AUTH_PROF_NAME) A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
                              WHERE INVEN_CATEGORY = 'SYS')                                                                                       
                              
                              
                                                                               
                              
SELECT     DISTINCT RTRIM(AP.AUTH_PROF_NAME) as AUTH_PROF_NAME,
            CASE A.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE A.RIGHT_LEVEL END AS [Activities],
            CASE B.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE B.RIGHT_LEVEL END As [Contract],
            CASE C.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE C.RIGHT_LEVEL END AS [Technical Docs],
            CASE D.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE D.RIGHT_LEVEL END AS [CA Items],
            CASE E.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE E.RIGHT_LEVEL END AS [Financial Migration],
            CASE F.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE F.RIGHT_LEVEL END AS [Financial Transactions],
            CASE G.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE G.RIGHT_LEVEL END AS [Manual Entries],
            CASE H.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE H.RIGHT_LEVEL END AS [Processing Management],
            CASE I.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE I.RIGHT_LEVEL END AS [Party],
            CASE J.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE J.RIGHT_LEVEL END AS [System Management],
            CASE K.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE K.RIGHT_LEVEL END AS [PARTY APPEAL],
            CASE L.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE L.RIGHT_LEVEL END AS [ASSETS],
            CASE M.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE M.RIGHT_LEVEL END AS [CLAIM HEADER],
            CASE N.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE N.RIGHT_LEVEL END AS [GL ACCOUNTING],
            CASE O.RIGHT_LEVEL WHEN 'UPD' THEN 'Update' WHEN 'VEW' THEN 'View' WHEN NULL THEN 'No Access' ELSE O.RIGHT_LEVEL END AS [GL INTERFACE]

FROM RI.RIAUTHENTT RIA
LEFT JOIN [RI].[RIAUTHPROF] AP on RIA.AUTH_PRF_SEQ_NUM= AP.AUTH_PRF_SEQ_NUM
LEFT JOIN [ACTIVITIES] A on A.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
LEFT JOIN [CONTRACT] B on B.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
LEFT JOIN [Technical Documents] C on C.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
LEFT JOIN [CA Items]D on D.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
LEFT JOIN [Financial Migration] E on E.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
LEFT JOIN [Financial Transactions] F on F.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
LEFT JOIN [Manual Entries] G on G.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
LEFT JOIN [Processing Management] H on H.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
LEFT JOIN [Party] I on I.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
LEFT JOIN [System Management] J on J.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
LEFT JOIN [PARTY APPEAL] K on K.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
LEFT JOIN [ASSETS] L on L.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
LEFT JOIN [CLAIM HEADER] M on M.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
LEFT JOIN [GL ACCOUNTING] N on N.AUTH_PROF_NAME = AP.AUTH_PROF_NAME
LEFT JOIN [GL INTERFACE] O on O.AUTH_PROF_NAME = AP.AUTH_PROF_NAME