Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=0 where ServiceLevelAgreementID=1
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=4 where ServiceLevelAgreementID=2
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=8 where ServiceLevelAgreementID=3
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=48 where ServiceLevelAgreementID=4
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=72 where ServiceLevelAgreementID=5
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=0 where ServiceLevelAgreementID=32
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=0 where ServiceLevelAgreementID=33
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=0 where ServiceLevelAgreementID=34
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=0 where ServiceLevelAgreementID=35
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=0 where ServiceLevelAgreementID=36
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=0 where ServiceLevelAgreementID=37
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=4 where ServiceLevelAgreementID=38
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=24 where ServiceLevelAgreementID=39
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=24 where ServiceLevelAgreementID=40
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=24 where ServiceLevelAgreementID=41
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=48 where ServiceLevelAgreementID=42
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=120 where ServiceLevelAgreementID=43
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=48 where ServiceLevelAgreementID=44
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=48 where ServiceLevelAgreementID=45
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=48 where ServiceLevelAgreementID=46
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=72 where ServiceLevelAgreementID=47
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=72 where ServiceLevelAgreementID=48
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=96 where ServiceLevelAgreementID=49
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=120 where ServiceLevelAgreementID=50
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=240 where ServiceLevelAgreementID=51
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=72 where ServiceLevelAgreementID=52
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=72 where ServiceLevelAgreementID=53
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=120 where ServiceLevelAgreementID=54
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=120 where ServiceLevelAgreementID=55
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=120 where ServiceLevelAgreementID=56
Update [ServiceCatalog].[dbo].[ServiceLevelAgreement] set BusinessHours=240 where ServiceLevelAgreementID=57