//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationAccess.srRSSE {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.trg.com/", ConfigurationName="srRSSE.clsScriptEngineSoap")]
    public interface clsScriptEngineSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trg.com/ExecuteScript", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ExecuteScript(string InputDSString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trg.com/ExecuteScript", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ExecuteScriptAsync(string InputDSString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trg.com/ExecuteScriptXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ExecuteScriptXml(string InputDSString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.trg.com/ExecuteScriptXml", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ExecuteScriptXmlAsync(string InputDSString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface clsScriptEngineSoapChannel : ApplicationAccess.srRSSE.clsScriptEngineSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class clsScriptEngineSoapClient : System.ServiceModel.ClientBase<ApplicationAccess.srRSSE.clsScriptEngineSoap>, ApplicationAccess.srRSSE.clsScriptEngineSoap {
        
        public clsScriptEngineSoapClient() {
        }
        
        public clsScriptEngineSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public clsScriptEngineSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public clsScriptEngineSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public clsScriptEngineSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ExecuteScript(string InputDSString) {
            return base.Channel.ExecuteScript(InputDSString);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ExecuteScriptAsync(string InputDSString) {
            return base.Channel.ExecuteScriptAsync(InputDSString);
        }
        
        public System.Xml.XmlNode ExecuteScriptXml(string InputDSString) {
            return base.Channel.ExecuteScriptXml(InputDSString);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ExecuteScriptXmlAsync(string InputDSString) {
            return base.Channel.ExecuteScriptXmlAsync(InputDSString);
        }
    }
}
