 Use [SSISDB]
 Go
 
 
 -------- Sapiens Claims Feed Validation  ENVIRONMENT VARIABLE VALUES ------



-- Environment Variable SapiensClaimsFeed\SapiensClaimsFeed _Dev\SapiensEmailRecipients
Declare @SapiensEmailRecipients sql_variant = N'Roja_Kasula@trg.com'


-- Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SendMailConnection
Declare @SQLSrcConnection sql_variant = N'Data Source=DWDEV;Initial Catalog=RS_ODS;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;'
-- Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\ServerName
Declare @ServerName sql_variant = N'DWDEV'

-- Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SendMailConnection
Declare @SendMailConnection sql_variant = N'Data Source=ManDevbs01;Initial Catalog=ITProductionSupport;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;'

-- Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\ServerName
Declare @MailServerName sql_variant = N'ManDevbs01'



 ---------------------------------

/*
Script Name: C:\DevTeamWork\Operations\SSIS\SapiensClaimFeedBalanceValidationValidation\EnvironmentScripts\SISDB_SapiensClaimFeedBalanceValidation_SapiensClaimFeedBalanceValidation_Dev.environment.sql
Generated From Catalog Instance: DWDEV
Catalog Name: SSISDB
Folder Name: SapiensClaimFeedBalanceValidation
Environment Name: SapiensClaimFeedBalanceValidation_Dev
Generated By: TRG\rkasu
Generated Date: 4/25/2017 2:24:51 PM
Generated From: CatalogBase v1.1.1.0 executing on: RKASU-LAP
*/

print 'Script Name: C:\DevTeamWorkRequirementDocs\SapiensClaimFeedBalanceValidationValidate\SapiensClaimFeedBalanceValidation\4_BIDevETL01_SSISDB_SapiensClaimFeedBalanceValidation_SapiensClaimFeedBalanceValidation_Dev.environment.sql
Generated From Catalog Instance: BIETL01
Catalog Name: SSISDB
Folder Name: SapiensClaimFeedBalanceValidation
Environment Name: SapiensClaimFeedBalanceValidation_Dev
Generated By: TRG\rkasu
Generated Date: 2/22/2017 2:24:51 PM
Generated From: CatalogBase v1.1.1.0 executing on: RKASU-LAP'
print ''
print '------------------------------------------------------------'
print 'Deployed to Instance: ' + @@servername
print 'Deploy Date: ' + Convert(varchar,GetDate(), 101) + ' ' + Convert(varchar,GetDate(), 108)
print 'Deployed By: ' + original_login()
print '------------------------------------------------------------'
print ''

 -- Environment SSISDB\SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev
print 'Environment SSISDB\SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev'
If Not Exists(Select * 
           From SSISDB.[catalog].environments e 
           Join SSISDB.[catalog].folders f 
             On f.folder_id = e.folder_id 
           Where e.name = N'SapiensClaimFeedBalanceValidation_Dev'
             And f.name = N'SapiensClaimFeedBalanceValidation')

 begin
  print ' - Creating Environment SSISDB\SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev'

  Exec SSISDB.[catalog].create_environment 
      @environment_name=N'SapiensClaimFeedBalanceValidation_Dev'
    , @folder_name=N'SapiensClaimFeedBalanceValidation'
  print ' - Environment SSISDB\SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev created'
 end
else
 print ' - Environment SSISDB\SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev already exists.'
print ''


-- Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SapiensEmailRecipients
print 'Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SapiensEmailRecipients'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'SapiensClaimFeedBalanceValidation_Dev' 
			And ev.name = N'SapiensEmailRecipients' 
			And f.name = N'SapiensClaimFeedBalanceValidation') 
 begin
  print ' - Dropping Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SapiensEmailRecipients'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'SapiensEmailRecipients' 
  , @environment_name=N'SapiensClaimFeedBalanceValidation_Dev' 
  , @folder_name=N'SapiensClaimFeedBalanceValidation' 
  print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SapiensEmailRecipients dropped'
 end
print ' - Creating Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SapiensEmailRecipients'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'SapiensEmailRecipients'
    , @sensitive = 0
    , @environment_name = N'SapiensClaimFeedBalanceValidation_Dev'
    , @folder_name = N'SapiensClaimFeedBalanceValidation'
    , @value = @SapiensEmailRecipients
    , @data_type = N'String'

print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SapiensEmailRecipients created'

-- Set Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SapiensEmailRecipients
print ' - Set Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SapiensEmailRecipients value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'SapiensEmailRecipients' 
    , @environment_name = N'SapiensClaimFeedBalanceValidation_Dev' 
    , @folder_name = N'SapiensClaimFeedBalanceValidation' 
    , @value = @SapiensEmailRecipients
print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SapiensEmailRecipients value set'
print ''

-- Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SendMailConnection
print 'Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SendMailConnection'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'SapiensClaimFeedBalanceValidation_Dev' 
			And ev.name = N'SendMailConnection' 
			And f.name = N'SapiensClaimFeedBalanceValidation') 
 begin
  print ' - Dropping Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SendMailConnection'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'SendMailConnection' 
  , @environment_name=N'SapiensClaimFeedBalanceValidation_Dev' 
  , @folder_name=N'SapiensClaimFeedBalanceValidation' 
  print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SendMailConnection dropped'
 end
print ' - Creating Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SendMailConnection'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'SendMailConnection'
    , @sensitive = 0
    , @environment_name = N'SapiensClaimFeedBalanceValidation_Dev'
    , @folder_name = N'SapiensClaimFeedBalanceValidation'
    , @value = @SendMailConnection
    , @data_type = N'String'

print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SendMailConnection created'

-- Set Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SendMailConnection
print ' - Set Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SendMailConnection value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'SendMailConnection' 
    , @environment_name = N'SapiensClaimFeedBalanceValidation_Dev' 
    , @folder_name = N'SapiensClaimFeedBalanceValidation' 
    , @value = @SendMailConnection
print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SendMailConnection value set'
print ''

-- Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\MailServerName
print 'Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\MailServerName'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'SapiensClaimFeedBalanceValidation_Dev' 
			And ev.name = N'MailServerName' 
			And f.name = N'SapiensClaimFeedBalanceValidation') 
 begin
  print ' - Dropping Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\MailServerName'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'MailServerName' 
  , @environment_name=N'SapiensClaimFeedBalanceValidation_Dev' 
  , @folder_name=N'SapiensClaimFeedBalanceValidation' 
  print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\MailServerName dropped'
 end
print ' - Creating Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\MailServerName'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'MailServerName'
    , @sensitive = 0
    , @environment_name = N'SapiensClaimFeedBalanceValidation_Dev'
    , @folder_name = N'SapiensClaimFeedBalanceValidation'
    , @value = @MailServerName
    , @data_type = N'String'

print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\MailServerName created'

-- Set Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\ServerName
print ' - Set Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\MailServerName value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'MailServerName' 
    , @environment_name = N'SapiensClaimFeedBalanceValidation_Dev' 
    , @folder_name = N'SapiensClaimFeedBalanceValidation' 
    , @value = @MailServerName
print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\MailServerName value set'
print ''



-- Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SQLSrcConnection
print 'Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SQLSrcConnection'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'SapiensClaimFeedBalanceValidation_Dev' 
			And ev.name = N'SQLSrcConnection' 
			And f.name = N'SapiensClaimFeedBalanceValidation') 
 begin
  print ' - Dropping Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SQLSrcConnection'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'SQLSrcConnection' 
  , @environment_name=N'SapiensClaimFeedBalanceValidation_Dev' 
  , @folder_name=N'SapiensClaimFeedBalanceValidation' 
  print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SQLSrcConnection dropped'
 end
print ' - Creating Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SQLSrcConnection'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'SQLSrcConnection'
    , @sensitive = 0
    , @environment_name = N'SapiensClaimFeedBalanceValidation_Dev'
    , @folder_name = N'SapiensClaimFeedBalanceValidation'
    , @value = @SQLSrcConnection
    , @data_type = N'String'

print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SQLSrcConnection created'

-- Set Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SQLSrcConnection
print ' - Set Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SQLSrcConnection value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'SQLSrcConnection' 
    , @environment_name = N'SapiensClaimFeedBalanceValidation_Dev' 
    , @folder_name = N'SapiensClaimFeedBalanceValidation' 
    , @value = @SQLSrcConnection
print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\SQLSrcConnection value set'
print ''


-- Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\ServerName
print 'Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\ServerName'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'SapiensClaimFeedBalanceValidation_Dev' 
			And ev.name = N'ServerName' 
			And f.name = N'SapiensClaimFeedBalanceValidation') 
 begin
  print ' - Dropping Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\ServerName'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'ServerName' 
  , @environment_name=N'SapiensClaimFeedBalanceValidation_Dev' 
  , @folder_name=N'SapiensClaimFeedBalanceValidation' 
  print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\ServerName dropped'
 end
print ' - Creating Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\ServerName'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'ServerName'
    , @sensitive = 0
    , @environment_name = N'SapiensClaimFeedBalanceValidation_Dev'
    , @folder_name = N'SapiensClaimFeedBalanceValidation'
    , @value = @ServerName
    , @data_type = N'String'

print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\ServerName created'

-- Set Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\ServerName
print ' - Set Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\ServerName value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'ServerName' 
    , @environment_name = N'SapiensClaimFeedBalanceValidation_Dev' 
    , @folder_name = N'SapiensClaimFeedBalanceValidation' 
    , @value = @ServerName
print ' - Environment Variable SapiensClaimFeedBalanceValidation\SapiensClaimFeedBalanceValidation_Dev\ServerName value set'
print ''






