//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Link_GW_Docs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Link_GW_Docs.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OrderBy&gt;&lt;FieldRef Name=&quot;FileLeafRef&quot; /&gt;&lt;/OrderBy&gt;&lt;Where&gt;&lt;And&gt;&lt;IsNotNull&gt;&lt;FieldRef Name=&quot;DocIcon&quot; /&gt;&lt;/IsNotNull&gt;&lt;IsNull&gt;&lt;FieldRef Name=&quot;Work_x0020_Matter_x0020_Document&quot;/&gt;&lt;/IsNull&gt;&lt;/And&gt;&lt;/Where&gt;.
        /// </summary>
        internal static string CAMLQuery {
            get {
                return ResourceManager.GetString("CAMLQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link GW Docs.
        /// </summary>
        internal static string ErrorSource {
            get {
                return ResourceManager.GetString("ErrorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Matter Document.
        /// </summary>
        internal static string FieldBCSWorkMatterDocument {
            get {
                return ResourceManager.GetString("FieldBCSWorkMatterDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Matter Document: Status.
        /// </summary>
        internal static string FieldBCSWorkMatterDocumentStatus {
            get {
                return ResourceManager.GetString("FieldBCSWorkMatterDocumentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Category.
        /// </summary>
        internal static string FieldCategory {
            get {
                return ResourceManager.GetString("FieldCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ID.
        /// </summary>
        internal static string FieldDocumentId {
            get {
                return ResourceManager.GetString("FieldDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Status.
        /// </summary>
        internal static string FieldDocumentStatus {
            get {
                return ResourceManager.GetString("FieldDocumentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Sub Category.
        /// </summary>
        internal static string FieldSubCategory {
            get {
                return ResourceManager.GetString("FieldSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Required.
        /// </summary>
        internal static string FieldUpdateRequired {
            get {
                return ResourceManager.GetString("FieldUpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://records.trg.com/sites/Guidewire.
        /// </summary>
        internal static string SiteUrl {
            get {
                return ResourceManager.GetString("SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Matter Documents.
        /// </summary>
        internal static string WorkMatterDocumentsLibrary {
            get {
                return ResourceManager.GetString("WorkMatterDocumentsLibrary", resourceCulture);
            }
        }
    }
}
