/*
Script Name: H:\My SQL Code\Deployment Scripts\BIUATETL01\CFIGLFILES\\1_BIUATETL01_SSISDB_CFIGLFILES.folder.sql
Generated From Catalog Instance: BIUATETL01
Catalog Name: SSISDB
Folder Name: CFIGLFILES
Generated By: TRG\jgabe
Generated Date: 2/9/2018 9:32:24 AM
Generated From: CatalogBase v2.0.2.0 executing on: JGABEL-LAP1
*/

Use SSISDB 
go 

print 'Script Name: H:\My SQL Code\Deployment Scripts\BIUATETL01\CFIGLFILES\\1_BIUATETL01_SSISDB_CFIGLFILES.folder.sql
Generated From Catalog Instance: BIUATETL01
Catalog Name: SSISDB
Folder Name: CFIGLFILES
Generated By: TRG\jgabe
Generated Date: 2/9/2018 9:32:24 AM
Generated From: CatalogBase v2.0.2.0 executing on: JGABEL-LAP1'
print ''
print '------------------------------------------------------------'
print 'Deployed to Instance: ' + @@servername
print 'Deploy Date: ' + Convert(varchar,GetDate(), 101) + ' ' + Convert(varchar,GetDate(), 108)
print 'Deployed By: ' + original_login()
print '------------------------------------------------------------'
print ''
 -- SSISDB\CFIGLFILES

print 'Folder SSISDB\CFIGLFILES'
If Not Exists(Select * 
              From SSISDB.[catalog].folders 
              Where name = N'CFIGLFILES') 
 begin 
  print ' - Creating CFIGLFILES folder' 
  declare @folder_id bigint 
  Exec SSISDB.[catalog].create_folder 
       @folder_name = N'CFIGLFILES' 
     , @folder_id = @folder_id OUTPUT 
  print ' - CFIGLFILES folder created' 
 end 
else 
 begin 
  print ' - CFIGLFILES folder already exists.' 
 end 

 print ' - Setting CFIGLFILES folder description to ""' 
  Exec SSISDB.[catalog].set_folder_description 
       @folder_name = N'CFIGLFILES' 
     , @folder_description=N'' 
 print ' - CFIGLFILES folder description set to ""' 
go 