//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeOffCalendarSync {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeOffCalendarSync.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePoint - 80.
        /// </summary>
        internal static string DefaultWebApp {
            get {
                return ResourceManager.GetString("DefaultWebApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Off Calendar Sync Job.
        /// </summary>
        internal static string ErrorSource {
            get {
                return ResourceManager.GetString("ErrorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome1.
        /// </summary>
        internal static string EWSPassword {
            get {
                return ResourceManager.GetString("EWSPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeOff@TRG.com.
        /// </summary>
        internal static string EWSUserMailbox {
            get {
                return ResourceManager.GetString("EWSUserMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sptest@trg.com.
        /// </summary>
        internal static string EWSUsername {
            get {
                return ResourceManager.GetString("EWSUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.TimeOffCalendar_BulkUploadMerge.
        /// </summary>
        internal static string MergeStoredProcedureName {
            get {
                return ResourceManager.GetString("MergeStoredProcedureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=SPSQLN;Database=ExchangeCalendars;Integrated Security=true;.
        /// </summary>
        internal static string SqlConnectionString {
            get {
                return ResourceManager.GetString("SqlConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OU=_Active Associates,OU=People,DC=TRG,DC=com.
        /// </summary>
        internal static string SyncOU {
            get {
                return ResourceManager.GetString("SyncOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.TimeOffCalendar_TruncateAppointmentIds.
        /// </summary>
        internal static string TruncateStoredProcedureName {
            get {
                return ResourceManager.GetString("TruncateStoredProcedureName", resourceCulture);
            }
        }
    }
}
