//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltiProConsole.LoginService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationStatus", Namespace="http://www.ultipro.com/contracts")]
    public enum AuthenticationStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ultipro.com/services/loginservice", ConfigurationName="LoginService.ILoginService")]
    public interface ILoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ultipro.com/services/loginservice/ILoginService/Authenticate", ReplyAction="http://www.ultipro.com/services/loginservice/ILoginService/AuthenticateResponse")]
        UltiProConsole.LoginService.TokenResponse Authenticate(UltiProConsole.LoginService.TokenRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ultipro.com/services/loginservice/ILoginService/Authenticate", ReplyAction="http://www.ultipro.com/services/loginservice/ILoginService/AuthenticateResponse")]
        System.Threading.Tasks.Task<UltiProConsole.LoginService.TokenResponse> AuthenticateAsync(UltiProConsole.LoginService.TokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TokenRequest", WrapperNamespace="http://www.ultipro.com/contracts", IsWrapped=true)]
    public partial class TokenRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ultipro.com/services/loginservice")]
        public string ClientAccessKey;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ultipro.com/services/loginservice")]
        public string Password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ultipro.com/services/loginservice")]
        public string UserAccessKey;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.ultipro.com/services/loginservice")]
        public string UserName;
        
        public TokenRequest() {
        }
        
        public TokenRequest(string ClientAccessKey, string Password, string UserAccessKey, string UserName) {
            this.ClientAccessKey = ClientAccessKey;
            this.Password = Password;
            this.UserAccessKey = UserAccessKey;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TokenResponse", WrapperNamespace="http://www.ultipro.com/contracts", IsWrapped=true)]
    public partial class TokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ultipro.com/services/loginservice", Order=0)]
        public UltiProConsole.LoginService.AuthenticationStatus Status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ultipro.com/services/loginservice", Order=1)]
        public string StatusMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ultipro.com/services/loginservice", Order=2)]
        public string Token;
        
        public TokenResponse() {
        }
        
        public TokenResponse(UltiProConsole.LoginService.AuthenticationStatus Status, string StatusMessage, string Token) {
            this.Status = Status;
            this.StatusMessage = StatusMessage;
            this.Token = Token;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceChannel : UltiProConsole.LoginService.ILoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<UltiProConsole.LoginService.ILoginService>, UltiProConsole.LoginService.ILoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UltiProConsole.LoginService.TokenResponse UltiProConsole.LoginService.ILoginService.Authenticate(UltiProConsole.LoginService.TokenRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public UltiProConsole.LoginService.AuthenticationStatus Authenticate(string ClientAccessKey, string Password, string UserAccessKey, string UserName, out string StatusMessage, out string Token) {
            UltiProConsole.LoginService.TokenRequest inValue = new UltiProConsole.LoginService.TokenRequest();
            inValue.ClientAccessKey = ClientAccessKey;
            inValue.Password = Password;
            inValue.UserAccessKey = UserAccessKey;
            inValue.UserName = UserName;
            UltiProConsole.LoginService.TokenResponse retVal = ((UltiProConsole.LoginService.ILoginService)(this)).Authenticate(inValue);
            StatusMessage = retVal.StatusMessage;
            Token = retVal.Token;
            return retVal.Status;
        }
        
        public System.Threading.Tasks.Task<UltiProConsole.LoginService.TokenResponse> AuthenticateAsync(UltiProConsole.LoginService.TokenRequest request) {
            return base.Channel.AuthenticateAsync(request);
        }
    }
}
