USE [ServiceCatalog]
GO

/****** Object:  Table [dbo].[PickListItem]    Script Date: 4/13/2015 2:18:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PickListItem](
	[PickListItemID] [int] IDENTITY(1,1) NOT NULL,
	[PickListID] [int] NOT NULL,
	[Name] [varchar](200) NOT NULL,
 CONSTRAINT [PK_PickListItem] PRIMARY KEY CLUSTERED 
(
	[PickListItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PickListItem]  WITH CHECK ADD  CONSTRAINT [FK_PickListItem_PickList] FOREIGN KEY([PickListID])
REFERENCES [dbo].[PickList] ([PickListID])
GO

ALTER TABLE [dbo].[PickListItem] CHECK CONSTRAINT [FK_PickListItem_PickList]
GO


