USE [ServiceCatalog]
GO

/****** Object:  Table [dbo].[PickList]    Script Date: 4/13/2015 2:18:43 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PickList](
	[PickListID] [int] IDENTITY(1,1) NOT NULL,
	[Calculated] [bit] NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PickList] PRIMARY KEY CLUSTERED 
(
	[PickListID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


