//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePointUtilitiesLibraryTests {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class UnitTest : global::System.Configuration.ApplicationSettingsBase {
        
        private static UnitTest defaultInstance = ((UnitTest)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UnitTest())));
        
        public static UnitTest Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://rivernet2ndev.trg.com/sites/litman/Matters/LM000009999")]
        public string testWebUrl {
            get {
                return ((string)(this["testWebUrl"]));
            }
            set {
                this["testWebUrl"] = value;
            }
        }
    }
}
