/*
Script Name: H:\My SQL Code\Deployment Scripts\BIETL01\JAMS_Logging\\1_BIETL01_SSISDB_JAMS_Logging.folder.sql
Generated From Catalog Instance: BIETL01
Catalog Name: SSISDB
Folder Name: JAMS_Logging
Generated By: TRG\jgabe
Generated Date: 5/7/2018 1:54:49 PM
Generated From: CatalogBase v2.0.2.0 executing on: JGABEL-LAP1
*/

Use SSISDB 
go 

print 'Script Name: H:\My SQL Code\Deployment Scripts\BIETL01\JAMS_Logging\\1_BIETL01_SSISDB_JAMS_Logging.folder.sql
Generated From Catalog Instance: BIETL01
Catalog Name: SSISDB
Folder Name: JAMS_Logging
Generated By: TRG\jgabe
Generated Date: 5/7/2018 1:54:49 PM
Generated From: CatalogBase v2.0.2.0 executing on: JGABEL-LAP1'
print ''
print '------------------------------------------------------------'
print 'Deployed to Instance: ' + @@servername
print 'Deploy Date: ' + Convert(varchar,GetDate(), 101) + ' ' + Convert(varchar,GetDate(), 108)
print 'Deployed By: ' + original_login()
print '------------------------------------------------------------'
print ''
 -- SSISDB\JAMS_Logging

print 'Folder SSISDB\JAMS_Logging'
If Not Exists(Select * 
              From SSISDB.[catalog].folders 
              Where name = N'JAMS_Logging') 
 begin 
  print ' - Creating JAMS_Logging folder' 
  declare @folder_id bigint 
  Exec SSISDB.[catalog].create_folder 
       @folder_name = N'JAMS_Logging' 
     , @folder_id = @folder_id OUTPUT 
  print ' - JAMS_Logging folder created' 
 end 
else 
 begin 
  print ' - JAMS_Logging folder already exists.' 
 end 

 print ' - Setting JAMS_Logging folder description to ""' 
  Exec SSISDB.[catalog].set_folder_description 
       @folder_name = N'JAMS_Logging' 
     , @folder_description=N'' 
 print ' - JAMS_Logging folder description set to ""' 
go 
