Use SSISDB
Go

/*
Script Name: C:\ProdTeamWork\Operations\SSIS\ePAM_Import\Database\ePAM_Import\1_BIUATETL01_SSISDB_ePAM_Import.folder.sql
Generated From Catalog Instance: BIUATETL01
Catalog Name: SSISDB
Folder Name: ePAM_Import
Generated By: TRG\rkasu
Generated Date: 11/15/2017 11:49:21 AM
Generated From: CatalogBase v1.1.1.0 executing on: RKASU-LAP
*/

print 'Script Name: C:\ProdTeamWork\Operations\SSIS\ePAM_Import\Database\ePAM_Import\1_BIUATETL01_SSISDB_ePAM_Import.folder.sql
Generated From Catalog Instance: BIUATETL01
Catalog Name: SSISDB
Folder Name: ePAM_Import
Generated By: TRG\rkasu
Generated Date: 12/11/2017 11:49:21 AM
Generated From: CatalogBase v1.1.1.0 executing on: RKASU-LAP'
print ''
print '------------------------------------------------------------'
print 'Deployed to Instance: ' + @@servername
print 'Deploy Date: ' + Convert(varchar,GetDate(), 101) + ' ' + Convert(varchar,GetDate(), 108)
print 'Deployed By: ' + original_login()
print '------------------------------------------------------------'
print ''
 -- SSISDB\ePAM_Import

print 'Folder SSISDB\ePAM_Import'
If Not Exists(Select * 
              From SSISDB.[catalog].folders 
              Where name = N'ePAM_Import') 
 begin 
  print ' - Creating ePAM_Import folder' 
  declare @folder_id bigint 
  Exec SSISDB.[catalog].create_folder 
       @folder_name = N'ePAM_Import' 
     , @folder_id = @folder_id OUTPUT 
  print ' - ePAM_Import folder created' 
 end 
else 
 begin 
  print ' - ePAM_Import folder already exists.' 
 end 

 print ' - Setting ePAM_Import folder description to ""' 
  Exec SSISDB.[catalog].set_folder_description 
       @folder_name = N'ePAM_Import' 
     , @folder_description=N'' 
 print ' - ePAM_Import folder description set to ""' 
go 