 -- ENV_OPSDW_AG_Refresh ENVIRONMENT VARIABLE VALUES --

-- Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conAG_CS
Declare @conAG_CS_0 sql_variant = N''

-- Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conOPSDWPS_CS
Declare @conOPSDWPS_CS_1 sql_variant = N''

 ---------------------------------

/*
Script Name: H:\My SQL Code\Deployment Scripts\BIQAETL01\BIUATETL01\OPSDW_AG_Refresh\\4_BIQAETL01\BIUATETL01_SSISDB_OPSDW_AG_Refresh_ENV_OPSDW_AG_Refresh.environment.sql
Generated From Catalog Instance: BIQAETL01\BIUATETL01
Catalog Name: SSISDB
Folder Name: OPSDW_AG_Refresh
Environment Name: ENV_OPSDW_AG_Refresh
Generated By: TRG\jgabe
Generated Date: 2/23/2018 1:38:05 PM
Generated From: CatalogBase v2.0.2.0 executing on: JGABEL-LAP1
*/

print 'Script Name: H:\My SQL Code\Deployment Scripts\BIQAETL01\BIUATETL01\OPSDW_AG_Refresh\\4_BIQAETL01\BIUATETL01_SSISDB_OPSDW_AG_Refresh_ENV_OPSDW_AG_Refresh.environment.sql
Generated From Catalog Instance: BIQAETL01\BIUATETL01
Catalog Name: SSISDB
Folder Name: OPSDW_AG_Refresh
Environment Name: ENV_OPSDW_AG_Refresh
Generated By: TRG\jgabe
Generated Date: 2/23/2018 1:38:05 PM
Generated From: CatalogBase v2.0.2.0 executing on: JGABEL-LAP1'
print ''
print '------------------------------------------------------------'
print 'Deployed to Instance: ' + @@servername
print 'Deploy Date: ' + Convert(varchar,GetDate(), 101) + ' ' + Convert(varchar,GetDate(), 108)
print 'Deployed By: ' + original_login()
print '------------------------------------------------------------'
print ''
declare @ErrMsg varchar(100) 
print 'Check for folder: OPSDW_AG_Refresh ' 
If Not Exists(Select name 
              From SSISDB.[catalog].folders 
              Where name = N'OPSDW_AG_Refresh') 
 begin 
  set @ErrMsg = ' - OPSDW_AG_Refresh does not exist.' 
  raisError(@ErrMsg, 16, 1) 
  return 
 end 
Else 
 begin 
  print ' - OPSDW_AG_Refresh folder exists.' 
 end 
print '' 

 -- Environment SSISDB\OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh
print 'Environment SSISDB\OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh'
If Not Exists(Select * 
           From SSISDB.[catalog].environments e 
           Join SSISDB.[catalog].folders f 
             On f.folder_id = e.folder_id 
           Where e.name = N'ENV_OPSDW_AG_Refresh'
             And f.name = N'OPSDW_AG_Refresh')

 begin
  print ' - Creating Environment SSISDB\OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh'

  Exec SSISDB.[catalog].create_environment 
      @environment_name=N'ENV_OPSDW_AG_Refresh'
    , @folder_name=N'OPSDW_AG_Refresh'
  print ' - Environment SSISDB\OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh created'
 end
else
 print ' - Environment SSISDB\OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh already exists.'
print ''

-- Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conAG_CS
print 'Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conAG_CS'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
       Join SSISDB.[catalog].environments e 
On e.environment_id = ev.environment_id 
   Join SSISDB.[catalog].folders f 
On f.folder_id = e.folder_id 
   Where e.name = N'ENV_OPSDW_AG_Refresh' 
And ev.name = N'conAG_CS' 
And f.name = N'OPSDW_AG_Refresh') 
 begin
  print ' - Dropping Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conAG_CS'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'conAG_CS' 
  , @environment_name=N'ENV_OPSDW_AG_Refresh' 
  , @folder_name=N'OPSDW_AG_Refresh' 
  print ' - Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conAG_CS dropped'
 end
print ' - Creating Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conAG_CS'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'conAG_CS'
    , @sensitive = 0
    , @environment_name = N'ENV_OPSDW_AG_Refresh'
    , @folder_name = N'OPSDW_AG_Refresh'
    , @value = @conAG_CS_0
    , @data_type = N'String'

print ' - Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conAG_CS created'

-- Set Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conAG_CS
print ' - Set Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conAG_CS value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'conAG_CS' 
    , @environment_name = N'ENV_OPSDW_AG_Refresh' 
    , @folder_name = N'OPSDW_AG_Refresh' 
    , @value = @conAG_CS_0
print ' - Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conAG_CS value set'
print ''

-- Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conOPSDWPS_CS
print 'Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conOPSDWPS_CS'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
       Join SSISDB.[catalog].environments e 
On e.environment_id = ev.environment_id 
   Join SSISDB.[catalog].folders f 
On f.folder_id = e.folder_id 
   Where e.name = N'ENV_OPSDW_AG_Refresh' 
And ev.name = N'conOPSDWPS_CS' 
And f.name = N'OPSDW_AG_Refresh') 
 begin
  print ' - Dropping Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conOPSDWPS_CS'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'conOPSDWPS_CS' 
  , @environment_name=N'ENV_OPSDW_AG_Refresh' 
  , @folder_name=N'OPSDW_AG_Refresh' 
  print ' - Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conOPSDWPS_CS dropped'
 end
print ' - Creating Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conOPSDWPS_CS'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'conOPSDWPS_CS'
    , @sensitive = 0
    , @environment_name = N'ENV_OPSDW_AG_Refresh'
    , @folder_name = N'OPSDW_AG_Refresh'
    , @value = @conOPSDWPS_CS_1
    , @data_type = N'String'

print ' - Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conOPSDWPS_CS created'

-- Set Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conOPSDWPS_CS
print ' - Set Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conOPSDWPS_CS value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'conOPSDWPS_CS' 
    , @environment_name = N'ENV_OPSDW_AG_Refresh' 
    , @folder_name = N'OPSDW_AG_Refresh' 
    , @value = @conOPSDWPS_CS_1
print ' - Environment Variable OPSDW_AG_Refresh\ENV_OPSDW_AG_Refresh\conOPSDWPS_CS value set'
print ''