 -- PINSClaimsFTP_Prod ENVIRONMENT VARIABLE VALUES --

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPArchiveFlag
Declare @FTPArchiveFlag sql_variant = N'True'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPDeleteRemoteFileFlag
Declare @FTPDeleteRemoteFileFlag sql_variant = N'False'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask
Declare @FTPFileMask_Claim sql_variant = N'ODS_CLAIM_*'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask
Declare @FTPFileMask_Claimant sql_variant = N'ODS_CLAIMANT_*'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Cedent
Declare @FTPFileMask_Exposure sql_variant = N'ODS_Exposure_*'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Insured
Declare @FTPFileMask_Fianancial sql_variant = N'ODS_Financial_*'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalArchiveFolder
Declare @FTPLocalArchiveFolder sql_variant = N'\\ManSan02\Batch$\ETL\PINS\Claim\Archive\'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalFolder
Declare @FTPLocalFolder sql_variant = N'\\ManSan02\Batch$\ETL\PINS\Claim\'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPPassword
Declare @FTPPassword sql_variant = N'ShareWithUs1!'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPRemoteFolder
Declare @FTPRemoteFolder sql_variant = N'/US_Data_Transfer/Prod/ODS/'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPServer
Declare @FTPServer sql_variant = N'rsml.sharefileftp.com'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPUserID
Declare @FTPUserID sql_variant = N'ud463dfcd5'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\Password
Declare @Password sql_variant = N'/* MANUALLY SET SENSITIVE PARAMETER VALUE HERE */'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ClaimEmailRecipients
Declare @ClaimEmailRecipients sql_variant = N'Roja_Kasula@trg.com'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\SendMailConnection
Declare @SendMailConnection sql_variant = N'Data Source=ManProdbs01;Initial Catalog=ITProductionSupport;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;'

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ServerName
Declare @ServerName sql_variant = N'Manprodbs01'


 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

/*
Script Name: C:\ProdTeamWorkRequirementDocs\PINS Claim\PINSClaimsFTP\4_BIProdETL01_SSISDB_PINSClaimsFTP_PINSClaimsFTP_Prod.environment.sql
Generated From Catalog Instance: BIETL01
Catalog Name: SSISDB
Folder Name: PINSClaimsFTP
Environment Name: PINSClaimsFTP_Prod
Generated By: TRG\rkasu
Generated Date: 2/22/2017 2:24:51 PM
Generated From: CatalogBase v1.1.1.0 executing on: RKASU-LAP
*/

print 'Script Name: C:\ProdTeamWorkRequirementDocs\PINS Claim\PINSClaimsFTP\4_BIETL01_SSISDB_PINSClaimsFTP_PINSClaimsFTP_Prod.environment.sql
Generated From Catalog Instance: BIETL01
Catalog Name: SSISDB
Folder Name: PINSClaimsFTP
Environment Name: PINSClaimsFTP_Prod
Generated By: TRG\rkasu
Generated Date: 2/22/2017 2:24:51 PM
Generated From: CatalogBase v1.1.1.0 executing on: RKASU-LAP'
print ''
print '------------------------------------------------------------'
print 'Deployed to Instance: ' + @@servername
print 'Deploy Date: ' + Convert(varchar,GetDate(), 101) + ' ' + Convert(varchar,GetDate(), 108)
print 'Deployed By: ' + original_login()
print '------------------------------------------------------------'
print ''

 -- Environment SSISDB\PINSClaimsFTP\PINSClaimsFTP_Prod
print 'Environment SSISDB\PINSClaimsFTP\PINSClaimsFTP_Prod'
If Not Exists(Select * 
           From SSISDB.[catalog].environments e 
           Join SSISDB.[catalog].folders f 
             On f.folder_id = e.folder_id 
           Where e.name = N'PINSClaimsFTP_Prod'
             And f.name = N'PINSClaimsFTP')

 begin
  print ' - Creating Environment SSISDB\PINSClaimsFTP\PINSClaimsFTP_Prod'

  Exec SSISDB.[catalog].create_environment 
      @environment_name=N'PINSClaimsFTP_Prod'
    , @folder_name=N'PINSClaimsFTP'
  print ' - Environment SSISDB\PINSClaimsFTP\PINSClaimsFTP_Prod created'
 end
else
 print ' - Environment SSISDB\PINSClaimsFTP\PINSClaimsFTP_Prod already exists.'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPArchiveFlag
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPArchiveFlag'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'FTPArchiveFlag' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPArchiveFlag'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'FTPArchiveFlag' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPArchiveFlag dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPArchiveFlag'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'FTPArchiveFlag'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @FTPArchiveFlag
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPArchiveFlag created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPArchiveFlag
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPArchiveFlag value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'FTPArchiveFlag' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @FTPArchiveFlag
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPArchiveFlag value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPDeleteRemoteFileFlag
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPDeleteRemoteFileFlag'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'FTPDeleteRemoteFileFlag' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPDeleteRemoteFileFlag'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'FTPDeleteRemoteFileFlag' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPDeleteRemoteFileFlag dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPDeleteRemoteFileFlag'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'FTPDeleteRemoteFileFlag'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @FTPDeleteRemoteFileFlag
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPDeleteRemoteFileFlag created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPDeleteRemoteFileFlag
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPDeleteRemoteFileFlag value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'FTPDeleteRemoteFileFlag' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @FTPDeleteRemoteFileFlag
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPDeleteRemoteFileFlag value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'FTPFileMask_Claim' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claim'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'FTPFileMask_Claim' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claim dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claim'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'FTPFileMask_Claim'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @FTPFileMask_Claim
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claim created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claim
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claim value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'FTPFileMask_Claim' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @FTPFileMask_Claim
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claim value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claimant
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claimant'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'FTPFileMask_Claimant' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claimant'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'FTPFileMask_Claimant' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claimant dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claimant'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'FTPFileMask_Claimant'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @FTPFileMask_Claimant
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claimant created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claimant
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claimant value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'FTPFileMask_Claimant' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @FTPFileMask_Claimant
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Claimant value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Exposure
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Exposure'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'FTPFileMask_Exposure' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Exposure'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'FTPFileMask_Exposure' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Exposure dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Exposure'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'FTPFileMask_Exposure'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @FTPFileMask_Exposure
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Exposure created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Exposure
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Exposure value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'FTPFileMask_Exposure' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @FTPFileMask_Exposure
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Exposure value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Financial
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Financial'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'FTPFileMask_Financial' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Financial'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'FTPFileMask_Financial' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Financial dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Financial'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'FTPFileMask_Financial'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @FTPFileMask_Fianancial
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Financial created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Financial
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Financial value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'FTPFileMask_Financial' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @FTPFileMask_Fianancial
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPFileMask_Financial value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalArchiveFolder
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalArchiveFolder'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'FTPLocalArchiveFolder' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalArchiveFolder'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'FTPLocalArchiveFolder' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalArchiveFolder dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalArchiveFolder'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'FTPLocalArchiveFolder'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @FTPLocalArchiveFolder
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalArchiveFolder created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalArchiveFolder
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalArchiveFolder value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'FTPLocalArchiveFolder' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @FTPLocalArchiveFolder
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalArchiveFolder value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalFolder
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalFolder'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'FTPLocalFolder' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalFolder'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'FTPLocalFolder' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalFolder dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalFolder'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'FTPLocalFolder'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @FTPLocalFolder
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalFolder created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalFolder
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalFolder value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'FTPLocalFolder' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @FTPLocalFolder
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPLocalFolder value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPPassword
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPPassword'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'FTPPassword' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPPassword'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'FTPPassword' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPPassword dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPPassword'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'FTPPassword'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @FTPPassword
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPPassword created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPPassword
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPPassword value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'FTPPassword' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @FTPPassword
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPPassword value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPRemoteFolder
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPRemoteFolder'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'FTPRemoteFolder' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPRemoteFolder'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'FTPRemoteFolder' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPRemoteFolder dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPRemoteFolder'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'FTPRemoteFolder'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @FTPRemoteFolder
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPRemoteFolder created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPRemoteFolder
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPRemoteFolder value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'FTPRemoteFolder' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @FTPRemoteFolder
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPRemoteFolder value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPServer
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPServer'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'FTPServer' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPServer'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'FTPServer' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPServer dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPServer'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'FTPServer'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @FTPServer
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPServer created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPServer
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPServer value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'FTPServer' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @FTPServer
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPServer value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPUserID
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPUserID'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'FTPUserID' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPUserID'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'FTPUserID' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPUserID dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPUserID'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'FTPUserID'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @FTPUserID
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPUserID created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPUserID
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPUserID value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'FTPUserID' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @FTPUserID
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\FTPUserID value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\Password
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\Password'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'Password' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\Password'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'Password' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\Password dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\Password'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'Password'
    , @sensitive = 1
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @Password
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\Password created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\Password
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\Password value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'Password' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @Password
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\Password value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ClaimEmailRecipients
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ClaimEmailRecipients'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'ClaimEmailRecipients' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ClaimEmailRecipients'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'ClaimEmailRecipients' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ClaimEmailRecipients dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ClaimEmailRecipients'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'ClaimEmailRecipients'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @ClaimEmailRecipients
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ClaimEmailRecipients created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ClaimEmailRecipients
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ClaimEmailRecipients value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'ClaimEmailRecipients' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @ClaimEmailRecipients
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ClaimEmailRecipients value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\SendMailConnection
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\SendMailConnection'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'SendMailConnection' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\SendMailConnection'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'SendMailConnection' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\SendMailConnection dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\SendMailConnection'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'SendMailConnection'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @SendMailConnection
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\SendMailConnection created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\SendMailConnection
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\SendMailConnection value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'SendMailConnection' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @SendMailConnection
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\SendMailConnection value set'
print ''

-- Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ServerName
print 'Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ServerName'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'PINSClaimsFTP_Prod' 
			And ev.name = N'ServerName' 
			And f.name = N'PINSClaimsFTP') 
 begin
  print ' - Dropping Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ServerName'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'ServerName' 
  , @environment_name=N'PINSClaimsFTP_Prod' 
  , @folder_name=N'PINSClaimsFTP' 
  print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ServerName dropped'
 end
print ' - Creating Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ServerName'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'ServerName'
    , @sensitive = 0
    , @environment_name = N'PINSClaimsFTP_Prod'
    , @folder_name = N'PINSClaimsFTP'
    , @value = @ServerName
    , @data_type = N'String'

print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ServerName created'

-- Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ServerName
print ' - Set Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ServerName value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'ServerName' 
    , @environment_name = N'PINSClaimsFTP_Prod' 
    , @folder_name = N'PINSClaimsFTP' 
    , @value = @ServerName
print ' - Environment Variable PINSClaimsFTP\PINSClaimsFTP_Prod\ServerName value set'
print ''

