 -- ZenithLoad_Env ENVIRONMENT VARIABLE VALUES --

-- Environment Variable ZenithLoad\ZenithLoad_Env\ArchiveDir
Declare @ArchiveDir sql_variant = N'\\mhtsan02\batch$\Zenith\History\'

-- Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_ODS
Declare @CS_RS_ODS sql_variant = N'Data Source= DWPROD;Initial Catalog=RS_ODS;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;'

-- Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_Stage
Declare @CS_RS_Stage sql_variant = N'Data Source= DWPROD;Initial Catalog=RS_Stage;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;'

-- Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_StageGlobal
Declare @CS_RS_StageGlobal sql_variant = N'Data Source= DWPROD;Initial Catalog=RS_StageGlobal;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;'

-- Environment Variable ZenithLoad\ZenithLoad_Env\CS_SMTP
Declare @CS_SMTP sql_variant = N'SmtpServer=manrelay01.trg.com;UseWindowsAuthentication=False;EnableSsl=False;Timeout=2000;'

-- Environment Variable ZenithLoad\ZenithLoad_Env\CS_SSISDB
Declare @CS_SSISDB sql_variant = N'Data Source= DWPROD;Initial Catalog=SSISDB;Provider=SQLNCLI11.1;Integrated Security=SSPI;Auto Translate=False;'

-- Environment Variable ZenithLoad\ZenithLoad_Env\Email_Distribution_List
Declare @Email_Distribution_List sql_variant = N'ITProductionSupport@trg.com'

-- Environment Variable ZenithLoad\ZenithLoad_Env\ServerName2
Declare @ServerName2 sql_variant = N'DWPROD'

-- Environment Variable ZenithLoad\ZenithLoad_Env\SourceFileRootDir
Declare @SourceFileRootDir sql_variant = N'\\mhtsan02\batch$\Zenith\'

 ---------------------------------

/*
Script Name: C:\Users\rkasu\Desktop\ZenithLoadEnvironmentScript\ZenithLoad\4_BIETL01_SSISDB_ZenithLoad_ZenithLoad_Env.environment.sql
Generated From Catalog Instance: BIETL01
Catalog Name: SSISDB
Folder Name: ZenithLoad
Environment Name: ZenithLoad_Env
Generated By: TRG\rkasu
Generated Date: 10/2/2017 12:59:48 PM
Generated From: CatalogBase v1.1.1.0 executing on: RKASU-LAP
*/

print 'Script Name: C:\Users\rkasu\Desktop\ZenithLoadEnvironmentScript\ZenithLoad\4_BIETL01_SSISDB_ZenithLoad_ZenithLoad_Env.environment.sql
Generated From Catalog Instance: BIETL01
Catalog Name: SSISDB
Folder Name: ZenithLoad
Environment Name: ZenithLoad_Env
Generated By: TRG\rkasu
Generated Date: 10/2/2017 12:59:48 PM
Generated From: CatalogBase v1.1.1.0 executing on: RKASU-LAP'
print ''
print '------------------------------------------------------------'
print 'Deployed to Instance: ' + @@servername
print 'Deploy Date: ' + Convert(varchar,GetDate(), 101) + ' ' + Convert(varchar,GetDate(), 108)
print 'Deployed By: ' + original_login()
print '------------------------------------------------------------'
print ''

 -- Environment SSISDB\ZenithLoad\ZenithLoad_Env
print 'Environment SSISDB\ZenithLoad\ZenithLoad_Env'
If Not Exists(Select * 
           From SSISDB.[catalog].environments e 
           Join SSISDB.[catalog].folders f 
             On f.folder_id = e.folder_id 
           Where e.name = N'ZenithLoad_Env'
             And f.name = N'ZenithLoad')

 begin
  print ' - Creating Environment SSISDB\ZenithLoad\ZenithLoad_Env'

  Exec SSISDB.[catalog].create_environment 
      @environment_name=N'ZenithLoad_Env'
    , @folder_name=N'ZenithLoad'
  print ' - Environment SSISDB\ZenithLoad\ZenithLoad_Env created'
 end
else
 print ' - Environment SSISDB\ZenithLoad\ZenithLoad_Env already exists.'
print ''

-- Environment Variable ZenithLoad\ZenithLoad_Env\ArchiveDir
print 'Environment Variable ZenithLoad\ZenithLoad_Env\ArchiveDir'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'ZenithLoad_Env' 
			And ev.name = N'ArchiveDir' 
			And f.name = N'ZenithLoad') 
 begin
  print ' - Dropping Environment Variable ZenithLoad\ZenithLoad_Env\ArchiveDir'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'ArchiveDir' 
  , @environment_name=N'ZenithLoad_Env' 
  , @folder_name=N'ZenithLoad' 
  print ' - Environment Variable ZenithLoad\ZenithLoad_Env\ArchiveDir dropped'
 end
print ' - Creating Environment Variable ZenithLoad\ZenithLoad_Env\ArchiveDir'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'ArchiveDir'
    , @sensitive = 0
    , @environment_name = N'ZenithLoad_Env'
    , @folder_name = N'ZenithLoad'
    , @value = @ArchiveDir
    , @data_type = N'String'

print ' - Environment Variable ZenithLoad\ZenithLoad_Env\ArchiveDir created'

-- Set Environment Variable ZenithLoad\ZenithLoad_Env\ArchiveDir
print ' - Set Environment Variable ZenithLoad\ZenithLoad_Env\ArchiveDir value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'ArchiveDir' 
    , @environment_name = N'ZenithLoad_Env' 
    , @folder_name = N'ZenithLoad' 
    , @value = @ArchiveDir
print ' - Environment Variable ZenithLoad\ZenithLoad_Env\ArchiveDir value set'
print ''

-- Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_ODS
print 'Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_ODS'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'ZenithLoad_Env' 
			And ev.name = N'CS_RS_ODS' 
			And f.name = N'ZenithLoad') 
 begin
  print ' - Dropping Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_ODS'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'CS_RS_ODS' 
  , @environment_name=N'ZenithLoad_Env' 
  , @folder_name=N'ZenithLoad' 
  print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_ODS dropped'
 end
print ' - Creating Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_ODS'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'CS_RS_ODS'
    , @sensitive = 0
    , @environment_name = N'ZenithLoad_Env'
    , @folder_name = N'ZenithLoad'
    , @value = @CS_RS_ODS
    , @data_type = N'String'

print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_ODS created'

-- Set Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_ODS
print ' - Set Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_ODS value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'CS_RS_ODS' 
    , @environment_name = N'ZenithLoad_Env' 
    , @folder_name = N'ZenithLoad' 
    , @value = @CS_RS_ODS
print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_ODS value set'
print ''

-- Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_Stage
print 'Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_Stage'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'ZenithLoad_Env' 
			And ev.name = N'CS_RS_Stage' 
			And f.name = N'ZenithLoad') 
 begin
  print ' - Dropping Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_Stage'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'CS_RS_Stage' 
  , @environment_name=N'ZenithLoad_Env' 
  , @folder_name=N'ZenithLoad' 
  print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_Stage dropped'
 end
print ' - Creating Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_Stage'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'CS_RS_Stage'
    , @sensitive = 0
    , @environment_name = N'ZenithLoad_Env'
    , @folder_name = N'ZenithLoad'
    , @value = @CS_RS_Stage
    , @data_type = N'String'

print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_Stage created'

-- Set Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_Stage
print ' - Set Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_Stage value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'CS_RS_Stage' 
    , @environment_name = N'ZenithLoad_Env' 
    , @folder_name = N'ZenithLoad' 
    , @value = @CS_RS_Stage
print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_Stage value set'
print ''

-- Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_StageGlobal
print 'Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_StageGlobal'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'ZenithLoad_Env' 
			And ev.name = N'CS_RS_StageGlobal' 
			And f.name = N'ZenithLoad') 
 begin
  print ' - Dropping Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_StageGlobal'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'CS_RS_StageGlobal' 
  , @environment_name=N'ZenithLoad_Env' 
  , @folder_name=N'ZenithLoad' 
  print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_StageGlobal dropped'
 end
print ' - Creating Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_StageGlobal'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'CS_RS_StageGlobal'
    , @sensitive = 0
    , @environment_name = N'ZenithLoad_Env'
    , @folder_name = N'ZenithLoad'
    , @value = @CS_RS_StageGlobal
    , @data_type = N'String'

print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_StageGlobal created'

-- Set Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_StageGlobal
print ' - Set Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_StageGlobal value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'CS_RS_StageGlobal' 
    , @environment_name = N'ZenithLoad_Env' 
    , @folder_name = N'ZenithLoad' 
    , @value = @CS_RS_StageGlobal
print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_RS_StageGlobal value set'
print ''

-- Environment Variable ZenithLoad\ZenithLoad_Env\CS_SMTP
print 'Environment Variable ZenithLoad\ZenithLoad_Env\CS_SMTP'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'ZenithLoad_Env' 
			And ev.name = N'CS_SMTP' 
			And f.name = N'ZenithLoad') 
 begin
  print ' - Dropping Environment Variable ZenithLoad\ZenithLoad_Env\CS_SMTP'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'CS_SMTP' 
  , @environment_name=N'ZenithLoad_Env' 
  , @folder_name=N'ZenithLoad' 
  print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_SMTP dropped'
 end
print ' - Creating Environment Variable ZenithLoad\ZenithLoad_Env\CS_SMTP'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'CS_SMTP'
    , @sensitive = 0
    , @environment_name = N'ZenithLoad_Env'
    , @folder_name = N'ZenithLoad'
    , @value = @CS_SMTP
    , @data_type = N'String'

print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_SMTP created'

-- Set Environment Variable ZenithLoad\ZenithLoad_Env\CS_SMTP
print ' - Set Environment Variable ZenithLoad\ZenithLoad_Env\CS_SMTP value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'CS_SMTP' 
    , @environment_name = N'ZenithLoad_Env' 
    , @folder_name = N'ZenithLoad' 
    , @value = @CS_SMTP
print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_SMTP value set'
print ''

-- Environment Variable ZenithLoad\ZenithLoad_Env\CS_SSISDB
print 'Environment Variable ZenithLoad\ZenithLoad_Env\CS_SSISDB'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'ZenithLoad_Env' 
			And ev.name = N'CS_SSISDB' 
			And f.name = N'ZenithLoad') 
 begin
  print ' - Dropping Environment Variable ZenithLoad\ZenithLoad_Env\CS_SSISDB'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'CS_SSISDB' 
  , @environment_name=N'ZenithLoad_Env' 
  , @folder_name=N'ZenithLoad' 
  print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_SSISDB dropped'
 end
print ' - Creating Environment Variable ZenithLoad\ZenithLoad_Env\CS_SSISDB'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'CS_SSISDB'
    , @sensitive = 0
    , @environment_name = N'ZenithLoad_Env'
    , @folder_name = N'ZenithLoad'
    , @value = @CS_SSISDB
    , @data_type = N'String'

print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_SSISDB created'

-- Set Environment Variable ZenithLoad\ZenithLoad_Env\CS_SSISDB
print ' - Set Environment Variable ZenithLoad\ZenithLoad_Env\CS_SSISDB value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'CS_SSISDB' 
    , @environment_name = N'ZenithLoad_Env' 
    , @folder_name = N'ZenithLoad' 
    , @value = @CS_SSISDB
print ' - Environment Variable ZenithLoad\ZenithLoad_Env\CS_SSISDB value set'
print ''

-- Environment Variable ZenithLoad\ZenithLoad_Env\Email_Distribution_List
print 'Environment Variable ZenithLoad\ZenithLoad_Env\Email_Distribution_List'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'ZenithLoad_Env' 
			And ev.name = N'Email_Distribution_List' 
			And f.name = N'ZenithLoad') 
 begin
  print ' - Dropping Environment Variable ZenithLoad\ZenithLoad_Env\Email_Distribution_List'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'Email_Distribution_List' 
  , @environment_name=N'ZenithLoad_Env' 
  , @folder_name=N'ZenithLoad' 
  print ' - Environment Variable ZenithLoad\ZenithLoad_Env\Email_Distribution_List dropped'
 end
print ' - Creating Environment Variable ZenithLoad\ZenithLoad_Env\Email_Distribution_List'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'Email_Distribution_List'
    , @sensitive = 0
    , @environment_name = N'ZenithLoad_Env'
    , @folder_name = N'ZenithLoad'
    , @value = @Email_Distribution_List
    , @data_type = N'String'

print ' - Environment Variable ZenithLoad\ZenithLoad_Env\Email_Distribution_List created'

-- Set Environment Variable ZenithLoad\ZenithLoad_Env\Email_Distribution_List
print ' - Set Environment Variable ZenithLoad\ZenithLoad_Env\Email_Distribution_List value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'Email_Distribution_List' 
    , @environment_name = N'ZenithLoad_Env' 
    , @folder_name = N'ZenithLoad' 
    , @value = @Email_Distribution_List
print ' - Environment Variable ZenithLoad\ZenithLoad_Env\Email_Distribution_List value set'
print ''

-- Environment Variable ZenithLoad\ZenithLoad_Env\ServerName2
print 'Environment Variable ZenithLoad\ZenithLoad_Env\ServerName2'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'ZenithLoad_Env' 
			And ev.name = N'ServerName2' 
			And f.name = N'ZenithLoad') 
 begin
  print ' - Dropping Environment Variable ZenithLoad\ZenithLoad_Env\ServerName2'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'ServerName2' 
  , @environment_name=N'ZenithLoad_Env' 
  , @folder_name=N'ZenithLoad' 
  print ' - Environment Variable ZenithLoad\ZenithLoad_Env\ServerName2 dropped'
 end
print ' - Creating Environment Variable ZenithLoad\ZenithLoad_Env\ServerName2'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'ServerName2'
    , @sensitive = 0
    , @environment_name = N'ZenithLoad_Env'
    , @folder_name = N'ZenithLoad'
    , @value = @ServerName2
    , @data_type = N'String'

print ' - Environment Variable ZenithLoad\ZenithLoad_Env\ServerName2 created'

-- Set Environment Variable ZenithLoad\ZenithLoad_Env\ServerName2
print ' - Set Environment Variable ZenithLoad\ZenithLoad_Env\ServerName2 value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'ServerName2' 
    , @environment_name = N'ZenithLoad_Env' 
    , @folder_name = N'ZenithLoad' 
    , @value = @ServerName2
print ' - Environment Variable ZenithLoad\ZenithLoad_Env\ServerName2 value set'
print ''

-- Environment Variable ZenithLoad\ZenithLoad_Env\SourceFileRootDir
print 'Environment Variable ZenithLoad\ZenithLoad_Env\SourceFileRootDir'
If Exists(Select * 
          From SSISDB.[catalog].environment_variables ev 
	       Join SSISDB.[catalog].environments e 
			On e.environment_id = ev.environment_id 
		   Join SSISDB.[catalog].folders f 
			On f.folder_id = e.folder_id 
		   Where e.name = N'ZenithLoad_Env' 
			And ev.name = N'SourceFileRootDir' 
			And f.name = N'ZenithLoad') 
 begin
  print ' - Dropping Environment Variable ZenithLoad\ZenithLoad_Env\SourceFileRootDir'
  Exec SSISDB.[catalog].delete_environment_variable 
    @variable_name=N'SourceFileRootDir' 
  , @environment_name=N'ZenithLoad_Env' 
  , @folder_name=N'ZenithLoad' 
  print ' - Environment Variable ZenithLoad\ZenithLoad_Env\SourceFileRootDir dropped'
 end
print ' - Creating Environment Variable ZenithLoad\ZenithLoad_Env\SourceFileRootDir'
Exec SSISDB.[catalog].create_environment_variable 
      @variable_name = N'SourceFileRootDir'
    , @sensitive = 0
    , @environment_name = N'ZenithLoad_Env'
    , @folder_name = N'ZenithLoad'
    , @value = @SourceFileRootDir
    , @data_type = N'String'

print ' - Environment Variable ZenithLoad\ZenithLoad_Env\SourceFileRootDir created'

-- Set Environment Variable ZenithLoad\ZenithLoad_Env\SourceFileRootDir
print ' - Set Environment Variable ZenithLoad\ZenithLoad_Env\SourceFileRootDir value'
Exec SSISDB.[catalog].set_environment_variable_value 
      @variable_name = N'SourceFileRootDir' 
    , @environment_name = N'ZenithLoad_Env' 
    , @folder_name = N'ZenithLoad' 
    , @value = @SourceFileRootDir
print ' - Environment Variable ZenithLoad\ZenithLoad_Env\SourceFileRootDir value set'
print ''