//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltiProConsole.EmployeeAddressService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PingResponse", Namespace="http://schemas.datacontract.org/2004/07/UltimateSoftware.WcfTypes.Base")]
    [System.SerializableAttribute()]
    public partial class PingResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppDomainNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallerIPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UltiProConsole.EmployeeAddressService.PingResponse ChildField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Specialized.NameValueCollection InformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ListenerUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetUriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppDomainName {
            get {
                return this.AppDomainNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AppDomainNameField, value) != true)) {
                    this.AppDomainNameField = value;
                    this.RaisePropertyChanged("AppDomainName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallerIPAddress {
            get {
                return this.CallerIPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CallerIPAddressField, value) != true)) {
                    this.CallerIPAddressField = value;
                    this.RaisePropertyChanged("CallerIPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UltiProConsole.EmployeeAddressService.PingResponse Child {
            get {
                return this.ChildField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildField, value) != true)) {
                    this.ChildField = value;
                    this.RaisePropertyChanged("Child");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionDetails {
            get {
                return this.ExceptionDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionDetailsField, value) != true)) {
                    this.ExceptionDetailsField = value;
                    this.RaisePropertyChanged("ExceptionDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Specialized.NameValueCollection Information {
            get {
                return this.InformationField;
            }
            set {
                if ((object.ReferenceEquals(this.InformationField, value) != true)) {
                    this.InformationField = value;
                    this.RaisePropertyChanged("Information");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListenerUri {
            get {
                return this.ListenerUriField;
            }
            set {
                if ((object.ReferenceEquals(this.ListenerUriField, value) != true)) {
                    this.ListenerUriField = value;
                    this.RaisePropertyChanged("ListenerUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineName {
            get {
                return this.MachineNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineNameField, value) != true)) {
                    this.MachineNameField = value;
                    this.RaisePropertyChanged("MachineName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessName {
            get {
                return this.ProcessNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessNameField, value) != true)) {
                    this.ProcessNameField = value;
                    this.RaisePropertyChanged("ProcessName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetUri {
            get {
                return this.TargetUriField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetUriField, value) != true)) {
                    this.TargetUriField = value;
                    this.RaisePropertyChanged("TargetUri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityIdentifier", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.EmployeeIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.EmployeeNumberIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.SsnIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.EmailAddressIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.UserDefinedIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.SinIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.NationalIdentifier))]
    public partial class EntityIdentifier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeIdentifier", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.EmployeeNumberIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.SsnIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.EmailAddressIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.UserDefinedIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.SinIdentifier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.NationalIdentifier))]
    public partial class EmployeeIdentifier : UltiProConsole.EmployeeAddressService.EntityIdentifier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeNumberIdentifier", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class EmployeeNumberIdentifier : UltiProConsole.EmployeeAddressService.EmployeeIdentifier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeNumber {
            get {
                return this.EmployeeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNumberField, value) != true)) {
                    this.EmployeeNumberField = value;
                    this.RaisePropertyChanged("EmployeeNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SsnIdentifier", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class SsnIdentifier : UltiProConsole.EmployeeAddressService.EmployeeIdentifier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SsnField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ssn {
            get {
                return this.SsnField;
            }
            set {
                if ((object.ReferenceEquals(this.SsnField, value) != true)) {
                    this.SsnField = value;
                    this.RaisePropertyChanged("Ssn");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailAddressIdentifier", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class EmailAddressIdentifier : UltiProConsole.EmployeeAddressService.EmployeeIdentifier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDefinedIdentifier", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class UserDefinedIdentifier : UltiProConsole.EmployeeAddressService.EmployeeIdentifier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinIdentifier", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class SinIdentifier : UltiProConsole.EmployeeAddressService.EmployeeIdentifier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SinField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sin {
            get {
                return this.SinField;
            }
            set {
                if ((object.ReferenceEquals(this.SinField, value) != true)) {
                    this.SinField = value;
                    this.RaisePropertyChanged("Sin");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NationalIdentifier", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class NationalIdentifier : UltiProConsole.EmployeeAddressService.EmployeeIdentifier {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalId {
            get {
                return this.NationalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalIdField, value) != true)) {
                    this.NationalIdField = value;
                    this.RaisePropertyChanged("NationalId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReadResponse", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.FindResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.AddressFindResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.GetResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.AddressGetResponse))]
    public partial class ReadResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UltiProConsole.EmployeeAddressService.Result OperationResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UltiProConsole.EmployeeAddressService.Result OperationResult {
            get {
                return this.OperationResultField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationResultField, value) != true)) {
                    this.OperationResultField = value;
                    this.RaisePropertyChanged("OperationResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasWarningsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UltiProConsole.EmployeeAddressService.OperationMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UltiProConsole.EmployeeAddressService.PagingInfo PagingInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RequestNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasErrors {
            get {
                return this.HasErrorsField;
            }
            set {
                if ((this.HasErrorsField.Equals(value) != true)) {
                    this.HasErrorsField = value;
                    this.RaisePropertyChanged("HasErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasWarnings {
            get {
                return this.HasWarningsField;
            }
            set {
                if ((this.HasWarningsField.Equals(value) != true)) {
                    this.HasWarningsField = value;
                    this.RaisePropertyChanged("HasWarnings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UltiProConsole.EmployeeAddressService.OperationMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UltiProConsole.EmployeeAddressService.PagingInfo PagingInfo {
            get {
                return this.PagingInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.PagingInfoField, value) != true)) {
                    this.PagingInfoField = value;
                    this.RaisePropertyChanged("PagingInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RequestNumber {
            get {
                return this.RequestNumberField;
            }
            set {
                if ((this.RequestNumberField.Equals(value) != true)) {
                    this.RequestNumberField = value;
                    this.RaisePropertyChanged("RequestNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FindResponse", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.AddressFindResponse))]
    public partial class FindResponse : UltiProConsole.EmployeeAddressService.ReadResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressFindResponse", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class AddressFindResponse : UltiProConsole.EmployeeAddressService.FindResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UltiProConsole.EmployeeAddressService.EmployeeAddress[] ResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UltiProConsole.EmployeeAddressService.EmployeeAddress[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetResponse", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.AddressGetResponse))]
    public partial class GetResponse : UltiProConsole.EmployeeAddressService.ReadResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressGetResponse", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class AddressGetResponse : UltiProConsole.EmployeeAddressService.GetResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UltiProConsole.EmployeeAddressService.Address[] ResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UltiProConsole.EmployeeAddressService.Address[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UltiProConsole.EmployeeAddressService.EmployeeIdentifier EmployeeIdentifierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateOrProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipOrPostalCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UltiProConsole.EmployeeAddressService.EmployeeIdentifier EmployeeIdentifier {
            get {
                return this.EmployeeIdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIdentifierField, value) != true)) {
                    this.EmployeeIdentifierField = value;
                    this.RaisePropertyChanged("EmployeeIdentifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateOrProvince {
            get {
                return this.StateOrProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.StateOrProvinceField, value) != true)) {
                    this.StateOrProvinceField = value;
                    this.RaisePropertyChanged("StateOrProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipOrPostalCode {
            get {
                return this.ZipOrPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipOrPostalCodeField, value) != true)) {
                    this.ZipOrPostalCodeField = value;
                    this.RaisePropertyChanged("ZipOrPostalCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingInfo", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class PagingInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage {
            get {
                return this.CurrentPageField;
            }
            set {
                if ((this.CurrentPageField.Equals(value) != true)) {
                    this.CurrentPageField = value;
                    this.RaisePropertyChanged("CurrentPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageTotal {
            get {
                return this.PageTotalField;
            }
            set {
                if ((this.PageTotalField.Equals(value) != true)) {
                    this.PageTotalField = value;
                    this.RaisePropertyChanged("PageTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItems {
            get {
                return this.TotalItemsField;
            }
            set {
                if ((this.TotalItemsField.Equals(value) != true)) {
                    this.TotalItemsField = value;
                    this.RaisePropertyChanged("TotalItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationMessage", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class OperationMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogEntryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UltiProConsole.EmployeeAddressService.Severity SeverityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogEntryId {
            get {
                return this.LogEntryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LogEntryIdField, value) != true)) {
                    this.LogEntryIdField = value;
                    this.RaisePropertyChanged("LogEntryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyName {
            get {
                return this.PropertyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyNameField, value) != true)) {
                    this.PropertyNameField = value;
                    this.RaisePropertyChanged("PropertyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UltiProConsole.EmployeeAddressService.Severity Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Severity", Namespace="http://www.ultipro.com/contracts")]
    public enum Severity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeAddress", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class EmployeeAddress : UltiProConsole.EmployeeAddressService.Employee {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UltiProConsole.EmployeeAddressService.Address[] AddressesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UltiProConsole.EmployeeAddressService.Address[] Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.EmployeeAddress))]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeNumber {
            get {
                return this.EmployeeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNumberField, value) != true)) {
                    this.EmployeeNumberField = value;
                    this.RaisePropertyChanged("EmployeeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeQuery", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class EmployeeQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullOrPartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastHireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationLevel1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationLevel2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationLevel3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationLevel4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalHireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupervisorLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeClockIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeNumber {
            get {
                return this.EmployeeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeNumberField, value) != true)) {
                    this.EmployeeNumberField = value;
                    this.RaisePropertyChanged("EmployeeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormerName {
            get {
                return this.FormerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FormerNameField, value) != true)) {
                    this.FormerNameField = value;
                    this.RaisePropertyChanged("FormerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullOrPartTime {
            get {
                return this.FullOrPartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.FullOrPartTimeField, value) != true)) {
                    this.FullOrPartTimeField = value;
                    this.RaisePropertyChanged("FullOrPartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastHire {
            get {
                return this.LastHireField;
            }
            set {
                if ((object.ReferenceEquals(this.LastHireField, value) != true)) {
                    this.LastHireField = value;
                    this.RaisePropertyChanged("LastHire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationLevel1 {
            get {
                return this.OrganizationLevel1Field;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationLevel1Field, value) != true)) {
                    this.OrganizationLevel1Field = value;
                    this.RaisePropertyChanged("OrganizationLevel1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationLevel2 {
            get {
                return this.OrganizationLevel2Field;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationLevel2Field, value) != true)) {
                    this.OrganizationLevel2Field = value;
                    this.RaisePropertyChanged("OrganizationLevel2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationLevel3 {
            get {
                return this.OrganizationLevel3Field;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationLevel3Field, value) != true)) {
                    this.OrganizationLevel3Field = value;
                    this.RaisePropertyChanged("OrganizationLevel3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationLevel4 {
            get {
                return this.OrganizationLevel4Field;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationLevel4Field, value) != true)) {
                    this.OrganizationLevel4Field = value;
                    this.RaisePropertyChanged("OrganizationLevel4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalHire {
            get {
                return this.OriginalHireField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalHireField, value) != true)) {
                    this.OriginalHireField = value;
                    this.RaisePropertyChanged("OriginalHire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PageNumberField, value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.PageSizeField, value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayGroup {
            get {
                return this.PayGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.PayGroupField, value) != true)) {
                    this.PayGroupField = value;
                    this.RaisePropertyChanged("PayGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupervisorLastName {
            get {
                return this.SupervisorLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupervisorLastNameField, value) != true)) {
                    this.SupervisorLastNameField = value;
                    this.RaisePropertyChanged("SupervisorLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminationDate {
            get {
                return this.TerminationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminationDateField, value) != true)) {
                    this.TerminationDateField = value;
                    this.RaisePropertyChanged("TerminationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeClockId {
            get {
                return this.TimeClockIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeClockIdField, value) != true)) {
                    this.TimeClockIdField = value;
                    this.RaisePropertyChanged("TimeClockId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WriteResponse", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.UpdateResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.AddressUpdateResponse))]
    public partial class WriteResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasWarningsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UltiProConsole.EmployeeAddressService.Result OperationResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UltiProConsole.EmployeeAddressService.Result[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasErrors {
            get {
                return this.HasErrorsField;
            }
            set {
                if ((this.HasErrorsField.Equals(value) != true)) {
                    this.HasErrorsField = value;
                    this.RaisePropertyChanged("HasErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasWarnings {
            get {
                return this.HasWarningsField;
            }
            set {
                if ((this.HasWarningsField.Equals(value) != true)) {
                    this.HasWarningsField = value;
                    this.RaisePropertyChanged("HasWarnings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UltiProConsole.EmployeeAddressService.Result OperationResult {
            get {
                return this.OperationResultField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationResultField, value) != true)) {
                    this.OperationResultField = value;
                    this.RaisePropertyChanged("OperationResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UltiProConsole.EmployeeAddressService.Result[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateResponse", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UltiProConsole.EmployeeAddressService.AddressUpdateResponse))]
    public partial class UpdateResponse : UltiProConsole.EmployeeAddressService.WriteResponse {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressUpdateResponse", Namespace="http://www.ultipro.com/contracts")]
    [System.SerializableAttribute()]
    public partial class AddressUpdateResponse : UltiProConsole.EmployeeAddressService.UpdateResponse {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ultipro.com/services/employeeaddress", ConfigurationName="EmployeeAddressService.IEmployeeAddress")]
    public interface IEmployeeAddress {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message PingRequest does not match the default value (http://www.ultipro.com/services/employeeaddress)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUesWcfService/Ping", ReplyAction="http://tempuri.org/IUesWcfService/PingResponse")]
        UltiProConsole.EmployeeAddressService.PingResponse1 Ping(UltiProConsole.EmployeeAddressService.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUesWcfService/Ping", ReplyAction="http://tempuri.org/IUesWcfService/PingResponse")]
        System.Threading.Tasks.Task<UltiProConsole.EmployeeAddressService.PingResponse1> PingAsync(UltiProConsole.EmployeeAddressService.PingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/GetAddressByEmpl" +
            "oyeeIdentifier", ReplyAction="http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/GetAddressByEmpl" +
            "oyeeIdentifierResponse")]
        UltiProConsole.EmployeeAddressService.AddressGetResponse GetAddressByEmployeeIdentifier(UltiProConsole.EmployeeAddressService.EmployeeIdentifier employeeIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/GetAddressByEmpl" +
            "oyeeIdentifier", ReplyAction="http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/GetAddressByEmpl" +
            "oyeeIdentifierResponse")]
        System.Threading.Tasks.Task<UltiProConsole.EmployeeAddressService.AddressGetResponse> GetAddressByEmployeeIdentifierAsync(UltiProConsole.EmployeeAddressService.EmployeeIdentifier employeeIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/FindAddresses", ReplyAction="http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/FindAddressesRes" +
            "ponse")]
        UltiProConsole.EmployeeAddressService.AddressFindResponse FindAddresses(UltiProConsole.EmployeeAddressService.EmployeeQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/FindAddresses", ReplyAction="http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/FindAddressesRes" +
            "ponse")]
        System.Threading.Tasks.Task<UltiProConsole.EmployeeAddressService.AddressFindResponse> FindAddressesAsync(UltiProConsole.EmployeeAddressService.EmployeeQuery query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/UpdateAddress", ReplyAction="http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/UpdateAddressRes" +
            "ponse")]
        UltiProConsole.EmployeeAddressService.AddressUpdateResponse UpdateAddress(UltiProConsole.EmployeeAddressService.Address[] entities);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/UpdateAddress", ReplyAction="http://www.ultipro.com/services/employeeaddress/IEmployeeAddress/UpdateAddressRes" +
            "ponse")]
        System.Threading.Tasks.Task<UltiProConsole.EmployeeAddressService.AddressUpdateResponse> UpdateAddressAsync(UltiProConsole.EmployeeAddressService.Address[] entities);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PingRequest {
        
        public PingRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PingResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public UltiProConsole.EmployeeAddressService.PingResponse PingResult;
        
        public PingResponse1() {
        }
        
        public PingResponse1(UltiProConsole.EmployeeAddressService.PingResponse PingResult) {
            this.PingResult = PingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeAddressChannel : UltiProConsole.EmployeeAddressService.IEmployeeAddress, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeAddressClient : System.ServiceModel.ClientBase<UltiProConsole.EmployeeAddressService.IEmployeeAddress>, UltiProConsole.EmployeeAddressService.IEmployeeAddress {
        
        public EmployeeAddressClient() {
        }
        
        public EmployeeAddressClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeAddressClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeAddressClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeAddressClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UltiProConsole.EmployeeAddressService.PingResponse1 UltiProConsole.EmployeeAddressService.IEmployeeAddress.Ping(UltiProConsole.EmployeeAddressService.PingRequest request) {
            return base.Channel.Ping(request);
        }
        
        public UltiProConsole.EmployeeAddressService.PingResponse Ping() {
            UltiProConsole.EmployeeAddressService.PingRequest inValue = new UltiProConsole.EmployeeAddressService.PingRequest();
            UltiProConsole.EmployeeAddressService.PingResponse1 retVal = ((UltiProConsole.EmployeeAddressService.IEmployeeAddress)(this)).Ping(inValue);
            return retVal.PingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UltiProConsole.EmployeeAddressService.PingResponse1> UltiProConsole.EmployeeAddressService.IEmployeeAddress.PingAsync(UltiProConsole.EmployeeAddressService.PingRequest request) {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<UltiProConsole.EmployeeAddressService.PingResponse1> PingAsync() {
            UltiProConsole.EmployeeAddressService.PingRequest inValue = new UltiProConsole.EmployeeAddressService.PingRequest();
            return ((UltiProConsole.EmployeeAddressService.IEmployeeAddress)(this)).PingAsync(inValue);
        }
        
        public UltiProConsole.EmployeeAddressService.AddressGetResponse GetAddressByEmployeeIdentifier(UltiProConsole.EmployeeAddressService.EmployeeIdentifier employeeIdentifier) {
            return base.Channel.GetAddressByEmployeeIdentifier(employeeIdentifier);
        }
        
        public System.Threading.Tasks.Task<UltiProConsole.EmployeeAddressService.AddressGetResponse> GetAddressByEmployeeIdentifierAsync(UltiProConsole.EmployeeAddressService.EmployeeIdentifier employeeIdentifier) {
            return base.Channel.GetAddressByEmployeeIdentifierAsync(employeeIdentifier);
        }
        
        public UltiProConsole.EmployeeAddressService.AddressFindResponse FindAddresses(UltiProConsole.EmployeeAddressService.EmployeeQuery query) {
            return base.Channel.FindAddresses(query);
        }
        
        public System.Threading.Tasks.Task<UltiProConsole.EmployeeAddressService.AddressFindResponse> FindAddressesAsync(UltiProConsole.EmployeeAddressService.EmployeeQuery query) {
            return base.Channel.FindAddressesAsync(query);
        }
        
        public UltiProConsole.EmployeeAddressService.AddressUpdateResponse UpdateAddress(UltiProConsole.EmployeeAddressService.Address[] entities) {
            return base.Channel.UpdateAddress(entities);
        }
        
        public System.Threading.Tasks.Task<UltiProConsole.EmployeeAddressService.AddressUpdateResponse> UpdateAddressAsync(UltiProConsole.EmployeeAddressService.Address[] entities) {
            return base.Channel.UpdateAddressAsync(entities);
        }
    }
}
