//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSERuleCopier.rulesengine {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="rulesengine.IRuleEngineSoapEndpoint")]
    public interface IRuleEngineSoapEndpoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleEngineSoapEndpoint/ExecuteRules", ReplyAction="http://tempuri.org/IRuleEngineSoapEndpoint/ExecuteRulesResponse")]
        System.Data.DataSet ExecuteRules(int ProcessId, int BatchId, bool DebugFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleEngineSoapEndpoint/ExecuteRulesEx", ReplyAction="http://tempuri.org/IRuleEngineSoapEndpoint/ExecuteRulesExResponse")]
        System.Data.DataSet ExecuteRulesEx(int ProcessId, int BatchId, bool DebugFlag, int StartRuleID, int StopRuleID, bool LoadLocalAtStart, bool WriteLocalAtEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRuleEngineSoapEndpoint/ServerStatus", ReplyAction="http://tempuri.org/IRuleEngineSoapEndpoint/ServerStatusResponse")]
        System.Data.DataSet ServerStatus();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRuleEngineSoapEndpointChannel : RSSERuleCopier.rulesengine.IRuleEngineSoapEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RuleEngineSoapEndpointClient : System.ServiceModel.ClientBase<RSSERuleCopier.rulesengine.IRuleEngineSoapEndpoint>, RSSERuleCopier.rulesengine.IRuleEngineSoapEndpoint {
        
        public RuleEngineSoapEndpointClient() {
        }
        
        public RuleEngineSoapEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RuleEngineSoapEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleEngineSoapEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleEngineSoapEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ExecuteRules(int ProcessId, int BatchId, bool DebugFlag) {
            return base.Channel.ExecuteRules(ProcessId, BatchId, DebugFlag);
        }
        
        public System.Data.DataSet ExecuteRulesEx(int ProcessId, int BatchId, bool DebugFlag, int StartRuleID, int StopRuleID, bool LoadLocalAtStart, bool WriteLocalAtEnd) {
            return base.Channel.ExecuteRulesEx(ProcessId, BatchId, DebugFlag, StartRuleID, StopRuleID, LoadLocalAtStart, WriteLocalAtEnd);
        }
        
        public System.Data.DataSet ServerStatus() {
            return base.Channel.ServerStatus();
        }
    }
}
