//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guidewire_Integration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Guidewire_Integration.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category and Sub Category.
        /// </summary>
        internal static string CategoryList {
            get {
                return ResourceManager.GetString("CategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list is used to populate document category sub-category..
        /// </summary>
        internal static string CategoryListDesc {
            get {
                return ResourceManager.GetString("CategoryListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GWBCS Endpoint.
        /// </summary>
        internal static string ConfigGWBCSEndpoint {
            get {
                return ResourceManager.GetString("ConfigGWBCSEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidewire WS Endpoint.
        /// </summary>
        internal static string ConfigGWWsEndpoint {
            get {
                return ResourceManager.GetString("ConfigGWWsEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidewire WS Password.
        /// </summary>
        internal static string ConfigGWWsPassword {
            get {
                return ResourceManager.GetString("ConfigGWWsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidewire WS Username.
        /// </summary>
        internal static string ConfigGWWsUserName {
            get {
                return ResourceManager.GetString("ConfigGWWsUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidewire System Configuration.
        /// </summary>
        internal static string ConfigurationList {
            get {
                return ResourceManager.GetString("ConfigurationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list is used to configure the Guidewire intergration.  Do not change these settings unless you are authorized to do so..
        /// </summary>
        internal static string ConfigurationListDesc {
            get {
                return ResourceManager.GetString("ConfigurationListDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRG\\SP2013QAAdmin.
        /// </summary>
        internal static string DefaultAdminAccount {
            get {
                return ResourceManager.GetString("DefaultAdminAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b50e3104-6812-424f-a011-cc90e6327318.
        /// </summary>
        internal static string DocIdFeatureGuid {
            get {
                return ResourceManager.GetString("DocIdFeatureGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7ad5272a-2694-4349-953e-ea5ef290e97c.
        /// </summary>
        internal static string DocumentRoutingFeatureGuid {
            get {
                return ResourceManager.GetString("DocumentRoutingFeatureGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidewire SharePoint Integration.
        /// </summary>
        internal static string ErrorSource {
            get {
                return ResourceManager.GetString("ErrorSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Document.
        /// </summary>
        internal static string FieldBCSVendorDocument {
            get {
                return ResourceManager.GetString("FieldBCSVendorDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Document: Status.
        /// </summary>
        internal static string FieldBCSVendorDocumentStatus {
            get {
                return ResourceManager.GetString("FieldBCSVendorDocumentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Matter Document.
        /// </summary>
        internal static string FieldBCSWorkMatterDocument {
            get {
                return ResourceManager.GetString("FieldBCSWorkMatterDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Matter Document: Status.
        /// </summary>
        internal static string FieldBCSWorkMatterDocumentStatus {
            get {
                return ResourceManager.GetString("FieldBCSWorkMatterDocumentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Category.
        /// </summary>
        internal static string FieldCategory {
            get {
                return ResourceManager.GetString("FieldCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string FieldCreatedBy {
            get {
                return ResourceManager.GetString("FieldCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string FieldCreatedDate {
            get {
                return ResourceManager.GetString("FieldCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string FieldDescription {
            get {
                return ResourceManager.GetString("FieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ID.
        /// </summary>
        internal static string FieldDocumentId {
            get {
                return ResourceManager.GetString("FieldDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _dlc_DocId.
        /// </summary>
        internal static string FieldDocumentIDString {
            get {
                return ResourceManager.GetString("FieldDocumentIDString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Status.
        /// </summary>
        internal static string FieldDocumentStatus {
            get {
                return ResourceManager.GetString("FieldDocumentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        internal static string FieldModifiedBy {
            get {
                return ResourceManager.GetString("FieldModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string FieldModifiedDate {
            get {
                return ResourceManager.GetString("FieldModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Sub Category.
        /// </summary>
        internal static string FieldSubCategory {
            get {
                return ResourceManager.GetString("FieldSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Required.
        /// </summary>
        internal static string FieldUpdateRequired {
            get {
                return ResourceManager.GetString("FieldUpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        internal static string FieldVendor {
            get {
                return ResourceManager.GetString("FieldVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Matter.
        /// </summary>
        internal static string FieldWorkMatter {
            get {
                return ResourceManager.GetString("FieldWorkMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 381029b9-d8b2-4fb4-84c0-f72f86993609.
        /// </summary>
        internal static string GuidewireIntegrationProvisioningFeatureGuid {
            get {
                return ResourceManager.GetString("GuidewireIntegrationProvisioningFeatureGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da2e115b-07e4-49d9-bb2c-35e93bb9fca9.
        /// </summary>
        internal static string InPlaceRecordsFeatureGuid {
            get {
                return ResourceManager.GetString("InPlaceRecordsFeatureGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riverstone Columns.
        /// </summary>
        internal static string RiverstoneColumnGroup {
            get {
                return ResourceManager.GetString("RiverstoneColumnGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riverstone Content Types.
        /// </summary>
        internal static string RiverStoneContentTypeGroup {
            get {
                return ResourceManager.GetString("RiverStoneContentTypeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/Guidewire.
        /// </summary>
        internal static string SiteServerRelativeUrl {
            get {
                return ResourceManager.GetString("SiteServerRelativeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContributeNoDelete.
        /// </summary>
        internal static string SpecialPermission {
            get {
                return ResourceManager.GetString("SpecialPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users can add and remove items but not delete. Also, no personal web parts..
        /// </summary>
        internal static string SpecialPermissionDesc {
            get {
                return ResourceManager.GetString("SpecialPermissionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlinked Documents.
        /// </summary>
        internal static string UnlinkedDocumentsView {
            get {
                return ResourceManager.GetString("UnlinkedDocumentsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidewire Vendor Document.
        /// </summary>
        internal static string VendorDocumentContentType {
            get {
                return ResourceManager.GetString("VendorDocumentContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Documents.
        /// </summary>
        internal static string VendorDocumentsLibrary {
            get {
                return ResourceManager.GetString("VendorDocumentsLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This library is used to store vendor documents..
        /// </summary>
        internal static string VendorDocumentsLibraryDesc {
            get {
                return ResourceManager.GetString("VendorDocumentsLibraryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidewire Work Matter Document.
        /// </summary>
        internal static string WorkMatterDocumentContentType {
            get {
                return ResourceManager.GetString("WorkMatterDocumentContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Matter Documents.
        /// </summary>
        internal static string WorkMatterDocumentsLibrary {
            get {
                return ResourceManager.GetString("WorkMatterDocumentsLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This library is used to store work matter documents..
        /// </summary>
        internal static string WorkMatterDocumentsLibraryDesc {
            get {
                return ResourceManager.GetString("WorkMatterDocumentsLibraryDesc", resourceCulture);
            }
        }
    }
}
